export default {
  FIREBASE_APP_API_KEY: '[YOUR CONFIG HERE]',
  FIREBASE_APP_AUTH_DOMAIN: '[YOUR CONFIG HERE]',
  FIREBASE_APP_DATABASE_URL: '[YOUR CONFIG HERE]',
  FIREBASE_APP_PRODJECT_ID: '[YOUR CONFIG HERE]',
  FIREBASE_APP_STORAGE_BUCKET: '[YOUR CONFIG HERE]',
  FIREBASE_APP_MESSAGING_SENDER_ID: '[YOUR CONFIG HERE]',
  FIREBASE_APP_ID: '[YOUR CONFIG HERE]',
};
